# Generated by Django 4.2.29 on 2026-04-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachments",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of attachment URLs with metadata",
            ),
        ),
    ]
