# Generated by Django 4.2.29 on 2026-04-04 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bidding", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_url", models.URLField(help_text="S3 URL to generated PDF")),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("total_hours", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_logs_count", models.IntegerField()),
                (
                    "report_id",
                    models.CharField(
                        help_text="Unique tamper-evident report ID",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_proof",
                        to="bidding.contract",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_proofs",
            },
        ),
        migrations.CreateModel(
            name="WorkLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField(help_text="What was done today")),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hours worked (e.g., 7.5)",
                        max_digits=4,
                    ),
                ),
                (
                    "screenshot_url",
                    models.URLField(blank=True, help_text="Optional screenshot proof"),
                ),
                (
                    "reference_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional reference link (GitHub, Figma, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_logs",
                        to="bidding.contract",
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "work_logs",
                "ordering": ["-date", "-created_at"],
                "unique_together": {("contract", "date")},
            },
        ),
        migrations.CreateModel(
            name="WeeklyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                (
                    "ai_summary",
                    models.TextField(help_text="AI-generated report content"),
                ),
                (
                    "pdf_url",
                    models.URLField(blank=True, help_text="S3 URL to generated PDF"),
                ),
                ("sent_to_client_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_reports",
                        to="bidding.contract",
                    ),
                ),
            ],
            options={
                "db_table": "weekly_reports",
                "ordering": ["-week_start"],
                "unique_together": {("contract", "week_start")},
            },
        ),
    ]
