# Generated by Django 4.2.29 on 2026-04-27 19:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bidding", "0002_review_reviewresponse_contractterminationrequest_and_more"),
        ("worklogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryproof",
            name="approved_deliverables",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="deliveryproof",
            name="total_deliverables",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="worklog",
            name="ai_generated_summary",
            field=models.TextField(
                blank=True, help_text="AI-generated summary from chat conversation"
            ),
        ),
        migrations.AddField(
            model_name="worklog",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worklog",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_work_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="worklog",
            name="client_notes",
            field=models.TextField(
                blank=True, help_text="Client feedback/notes on the work log"
            ),
        ),
        migrations.AddField(
            model_name="worklog",
            name="screenshot",
            field=models.ImageField(
                blank=True,
                help_text="Screenshot proof of work",
                null=True,
                upload_to="worklogs/screenshots/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="worklog",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="worklog",
            name="hours_worked",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Hours worked (e.g., 7.5)",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(24),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="worklog",
            name="screenshot_url",
            field=models.URLField(
                blank=True, help_text="Optional screenshot URL (legacy)"
            ),
        ),
        migrations.CreateModel(
            name="Deliverable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(help_text="Description of what was accomplished"),
                ),
                (
                    "ai_chat_transcript",
                    models.JSONField(
                        default=list, help_text="Full chat conversation with AI"
                    ),
                ),
                (
                    "ai_generated_report",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated report from chat conversation",
                    ),
                ),
                (
                    "attached_files",
                    models.JSONField(
                        default=list, help_text="List of attached file URLs"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted for Review"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("REVISION_REQUESTED", "Revision Requested"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("client_feedback", models.TextField(blank=True)),
                ("revision_notes", models.TextField(blank=True)),
                (
                    "hours_logged",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Hours associated with this deliverable",
                        max_digits=5,
                    ),
                ),
                ("payment_released", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverables",
                        to="bidding.contract",
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_deliverables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_deliverables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "deliverables",
                "ordering": ["-created_at"],
            },
        ),
    ]
