# Generated by Django 4.2.29 on 2026-04-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_remove_payment_razorpay_refund_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payout_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_payout_id",
            field=models.CharField(
                blank=True, help_text="RazorpayX Payout ID", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ESCROWED", "Escrowed"),
                    ("PAYOUT_PENDING", "Payout Pending"),
                    ("RELEASED", "Released"),
                    ("PAYOUT_FAILED", "Payout Failed"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
