# Generated by Django 4.2.29 on 2026-04-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_avatar_availability_deactivation"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
