# Generated by Django 4.2.29 on 2026-04-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancerprofile",
            name="razorpay_fund_account_id",
            field=models.CharField(
                blank=True,
                help_text="RazorpayX fund account ID for freelancer payouts",
                max_length=255,
            ),
        ),
    ]
