# Generated by Django 4.2.29 on 2026-04-04 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BID_SUBMITTED", "Bid Submitted"),
                            ("BID_ACCEPTED", "Bid Accepted"),
                            ("ESCROW_CREATED", "Escrow Created"),
                            ("LOG_SUBMITTED", "Log Submitted"),
                            ("REPORT_READY", "Report Ready"),
                            ("PAYMENT_RELEASED", "Payment Released"),
                            ("PROOF_READY", "Proof Ready"),
                            ("MESSAGE_RECEIVED", "Message Received"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_583549_idx",
                    )
                ],
            },
        ),
    ]
